### ISSUE TITLE
Discussion regarding your Palm OS game on reddit with feedback

### ISSUE THREAD

**Issue by jan-kleks** [captaintouch/palmGemPlucker#1]
Hello,

Sorry for bothering you, just wanted to let you know (I couldn't find your email address) that there is a discussion regarding your Minigolf project: https://old.reddit.com/r/Palm/comments/1f62b02/holy_smokes_i_just_released_a_minigolf_game_for/

Keep up the great work!

**Comment by captaintouch** [comment]
Thanks for pointing that out! Made a reddit account to comment :D
